# Generated by Django 3.2.8 on 2021-11-02 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="activities",
            old_name="name",
            new_name="title",
        ),
    ]
