# Generated by Django 3.2.8 on 2021-11-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_rename_name_activities_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activities",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
