# Generated by Django 3.2.8 on 2021-11-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_alter_activities_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissions",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="submissions",
                to="activities.activities",
            ),
        ),
    ]
